### ISSUE TITLE
Ordering of Reminder Panel by Date with reference to today

### ISSUE THREAD

**Issue by gabyang** [AY2223S1-CS2103T-W10-2/tp#75]
Feature should be broken down to 3 main subcomponents
- [ ] Storage to store outstanding tasks before application is closed
- [ ] Automatic reordering of all reminder tasks and birthdays once a new task is added
- [ ] On start-up, Reminder panel automatically shows all upcoming birthdays and loads up outstanding tasks
